name: 'Setup Selective'
description: 'Sets necessary environment variables for Selective'
author: 'Selective'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'terminal'
  color: 'blue'

inputs:
  runner-id:
    description: 'The index of the CI node as defined in the matrix'
  api-key:
    description: 'Your Selective Suite API Key'

runs:
  using: node20
  main: dist/index.js
